version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            circleci tests glob tests/func/test_*.py tests/unit/test_*.py | circleci tests split | pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports
